# Site settings
gems: [jekyll-paginate]
title: Information Business
description: > # this means to ignore newlines until "baseurl:"
  

# About Section
about: We are group of entrepreneurs specializing in creating, holding and supporting a wide spectrum of information based businesses.
mission:
  - Our first mission is to build infrastructure of web services to enrich the web e-commerce experience.

# Contact Information
telephone: 920005022
address: Firas Bin Nadr Street, Ulaya, Khobar, Saudi Arabia
email: info@iBusiness.sa

# Social Links
facebook: http://facebook.com
twitter: http://twitter.com
google: http://google.com
linkedin: http://linkedin.com
behance: http://behance.con
dribble: http://dribble.com
pinterest: http://pinterest.com

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    permalink: /projects/:title/
    output: true

# News
permalink: /news/:categories/:title
paginate_path: "/news/:num/"
paginate: 6
