# Site settings
title: Information Business
description: > # this means to ignore newlines until "baseurl:"
  Creative group of entrepreneurs specializing in all forms of information media

# About Section
about: We are a creative group of entrepreneurs specializing in all forms of information media.
mission: Our mission is to build eco-system of purposeful services for enriching the web e-commerce experience.

# Contact Information
telephone: 920005022
address: Firas Bin Nadr Street, Ulaya, Khobar, Saudi Arabia
email: info@example.com

# Social Links
facebook: http://facebook.com
twitter: http://twitter.com
google: http://google.com
linkedin: http://linkedin.com
behance: http://behance.con
dribble: http://dribble.com
pinterest: http://pinterest.com

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    permalink: /project/:path/
    output: true

