# Site settings
title: Information Business
description: > # this means to ignore newlines until "baseurl:"
  Creative group of entrepreneurs specializing in all forms of information media

# About Section
about: We are a creative group of entrepreneurs specializing in all forms of information media.
mission:
  - Our **mission** is to build eco-system of purposeful services for enriching the web e-commerce experience.
  - Our mission is to build eco-system of purposeful services for enriching the web e-commerce experience.
  - Our mission is to build eco-system of purposeful services for enriching the web e-commerce experience.
  - #Business Methodology

- ##Idea
  - ###Screening
  - ###Evaluation
  - ###Selection
- ##Brainstorming
  - ###Development
  - ###Approval
- ##Research
  - ###Data Collection
  - ###Market Research
- ##Analysis
  - ###Feasibility Study
  - ###Practicality Evaluation
- ##Requirements Preparation
  - ###Specifications
    - ####UI/UX Design
    - ####Technical Specification
    - ####Deployment Specification
  - ###Documentation
    - ####Workflows
    - ####Business Plan
    - ####Terms and Condition
    - ####Privacy Policy
- ##Resource Allocation
  - ###Investors
  - ###Contractors
- ##Entity Formation
  - ###Equity Distribution
  - ###Legal Representation
  - ###Copy write and Trademark
- ##Project Implementation
  - ###Employment and Development
  - ###Deployment and Training
- ##Quality Evaluation
  - ###Testing
  - ###Fixing the issues
- ##Launch
  - ###Beta
  - ###Management Guidelines
  - ###Marketing campaign
  - ###Live
- ##Return of Investment
  - ###Quarterly Reports
  - ###Annual Payouts
- ##Vision Implementation

# Contact Information
telephone: 920005022
address: Firas Bin Nadr Street, Ulaya, Khobar, Saudi Arabia
email: info@example.com

# Social Links
facebook: http://facebook.com
twitter: http://twitter.com
google: http://google.com
linkedin: http://linkedin.com
behance: http://behance.con
dribble: http://dribble.com
pinterest: http://pinterest.com

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    permalink: /projects/:title/
    output: true
